---
title: "Bias adjustment on temperature and precipitation using BCUH package"
author: "Olle Räty"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```
#Introduction

Bias correction has become de facto standard in climate studies, where model simulations are insufficient to provide reliable input for particular purposes as such. To this end, a number 
This tutorial illustrates the use of R package BCUH in which several bias correction and delta change methods have been implemented based on Räisänen and Räty (2013), Räty et al. (2014). In addition, a copula-based joint bias correction method designed for temperature and precipitation is available. The implementation of the copula-based algorithm is partially based on Li et al (2014), Gennaretti et al. (2015) and have been applied in the study by Räty el et. (submitted).

#Structure

The package has been built using the standard To provide the easy-to-access and up-to-date format the methods have been encapsulated as S4 methods in three different classes. 

#Univariate method

In the current format the package consists of 20 methods, which range from simple time mean scaling to more sophisticated quantile mapping methods, which have become popular in climate studies due to their relatively simple use. 

#Multivariate methods


#Examples

#Limitations

#Conclusions

#References
