---
title: "BCUH"
subtitle: "University of Helsinki bias adjustment tools"
author: "Olle Räty"
copyright: "Olle Räty"
output:
  packagedocs::package_docs:
    toc: true
    toc_collapse: false
redirect: http://ratyO.github.io/BCUH
vignette: |
  %\VignetteIndexEntry{BCUH Documentation}
  %\VignetteEngine{packagedocs::redirect}
navpills: |
  <li class="active"><a href='docs.html'>Docs</a></li>
  <li><a href='rd.html'>Package Ref</a></li>
  <li><a href='https://github.com/ratyO/BCUH'>Github <i class='fa fa-github'></i></a></li>
bibliography: bibliography.bib
---

```{r global_options, include=FALSE}
# R output pre blocks are styled by default to indicate output
knitr::opts_chunk$set(comment = NA)

# shorthand for rd_link() - see ?packagedocs::rd_link for more information
rdl <- function(x) packagedocs::rd_link(deparse(substitute(x)))
```

# BCUH

BCUH is a collection of simple univariate bi-variate methods for combining information obtained from reference data with (typically) climate simulations. These methods have become de facto standard in climate research due to the need to take biases in climate model simulations with respect to the observed climate into account. 

# Introduction

This tutorial illustrates the use of R package BCUH in which several bias correction and delta change methods have been implemented following [raisanen2013] and [raty2014]. In addition, a copula-based joint bias correction method designed for temperature and precipitation is available. The implementation of the copula-based algorithm is partially based on [li2014] with modifications from [gennaretti2015].

#Structure

All the statistical methods implemented in BCUH have been encapsulated as S4 methods belonging to a set of classes. To allow a simple access to these methods, they have been encapsulated mostly as

#Univariate method

In the current format the package consists of 20 methods, which range from simple time mean scaling to more sophisticated quantile mapping methods, which have become popular in climate studies due to their relatively simple use. 

#Multivariate methods

In the current version only the method originally developed by Li et al. (2014) with some improvements from. This method has been designed for joint bias correcting temperature and precipitation at different temporal scales. 

#Examples

In this section we give a set of examples, which demonstrate the use of BCUH. These examples are based on 

#Limitations

As with all statistical methods, there are several limitations for cases where BCUH can be used and when it is not feasible. First and most importantly, the implemented methods have not been designed to downscale climate model simulations, although this has commonly been a part of the procedure. This limitation is more severe for variables, whose spatial variability . Another . For non-parametric quantile mapping, an option is available to adjust changes in monthly means to the simulated ones. Higher monents have not been considered. This is not an issue in delta change method, which by definition add simulated changes to the observed time series based on . There are also more sophisticated methods, which pertain simulated changes at quantile level, while simultaneously pertain some of the advances of bias correction methods, i.e., the capability

#Other R packages

\code{BCUH} is just one of the possible R packages, which can be used to statistically adjust model simulations to biases in climate model simulations. In this section, a brief overview is given on the existing packages, which the reader might find useful. Another comprehensive package has been developed in Santander, which consists of a set of bias correction and statistical downscaling methods \url{https://github.com/SantanderMetGroup/downscaleR}. The package includes a set of tools for tailoring  climate model data for the implemented methods.

#Conclusions

#References


