---
title: "BCUH"
subtitle: "University of Helsinki bias adjustment tools"
author: "Olle Räty"
copyright: "Olle Räty"
output:
  packagedocs::package_docs:
    toc: true
    toc_collapse: false
redirect: http://ratyO.github.io/BCUH
vignette: |
  %\VignetteIndexEntry{BCUH Documentation}
  %\VignetteEngine{packagedocs::redirect}
navpills: |
  <li class="active"><a href='index.html'>Docs</a></li>
  <li><a href='rd.html'>Package Ref</a></li>
  <li><a href='https://github.com/ratyO/BCUH'>Github <i class='fa fa-github'></i></a></li>
bibliography: bibliography.bib
---

```{r global_options, include=FALSE}
# R output pre blocks are styled by default to indicate output
knitr::opts_chunk$set(comment = NA)

# shorthand for rd_link() - see ?packagedocs::rd_link for more information
rdl <- function(x) packagedocs::rd_link(deparse(substitute(x)))
```

# BCUH

Documentation under construction!!!

BCUH is a collection of simple univariate and bi-variate methods, which are used to combine information obtained from observation together with climate model simulations when constructing future temperature and precipitation projections.

# Introduction

This tutorial illustrates the use of R package BCUH in which several bias correction and delta change methods have been implemented following [raisanen2013] and [raty2014]. In addition, a copula-based joint bias correction method designed for temperature and precipitation is available. The implementation of the copula-based algorithm is partially based on [li2014] with modifications from [gennaretti2015]. These methods have become de facto standard in climate impact studies due to the need to take biases in climate model simulations with respect to the observed climate into account. An overview of the package structure is given together with a set of examples, which illustrate the use of the package. Also, the limitations of the implemented methods are discussed. Finally, we give a brief overview of other existing R tools, designed for similar purposes as BCUH. 

#Univariate method

The current version of BCUH contains 20 univariate methods in total. Ten of these methods have originally been designed for daily mean temperature, while the rest ten ten methods wre originally applied to daily precipitation. These methods range from simple time mean adjustment to more sophisticated parametric and non-parametric quantile mapping methods. All these methods have been implemented as methods for a set of S4 classes. To make the access to these methods easier, the package contains a wrapper function, which returns the adjusted data and the relevant meta data as an S4 object.


#Multivariate methods

In the current version of BCUH, only one bi-variate has been implementedis available to adjust the joint distribution of temperature and precipitation.  In this method the joint distribution of temperature and precipitation by first decomposing the joint distribution into separate marginal distributions. So far, only Gaussian copula is available in the package. The methods was originally introduced by Li et al. (2014) and further developed in Gennaretti et al. (2015). In this method the joint distribution of temperature and precipitation by first decomposing the joint distribution into separate marginal distributions.

#Limitations

As with all statistical methods, care should be taken, when applying BCUH to real-world data. There are several limitations to these methods. First and most importantly, the implemented  methods have not been designed for downscaling climate model simulations to higher resolutions. 
For non-parametric quantile mapping, an option is available to adjust changes in monthly means to the simulated ones. Higher monents have not been considered. This is not an issue in delta change method, which by definition add simulated changes to the observed time series based on. Other more sophisticated methods, which pertain simulated changes at quantile level, while simultaneously pertain some of the advances of bias correction methods, i.e., the capability

#Other R packages

\code{BCUH} is just one of the possible R packages, which can be used to statistically adjust model simulations to biases in climate model simulations. In this section, a brief overview is given on the existing packages, which the reader might find useful. Another comprehensive package has been developed in Santander, which consists of a set of bias correction and statistical downscaling methods \url{https://github.com/SantanderMetGroup/downscaleR}. The package includes a set of tools for tailoring  climate model data for the implemented methods.

#Conclusions

#References


